// types.js

// Auth Action Types
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOGOUT = 'LOGOUT';

// Job Action Types
export const FETCH_JOBS_REQUEST = 'FETCH_JOBS_REQUEST';
export const FETCH_JOBS_SUCCESS = 'FETCH_JOBS_SUCCESS';
export const FETCH_JOBS_FAILURE = 'FETCH_JOBS_FAILURE';

export const FETCH_JOB_DETAILS_REQUEST = 'FETCH_JOB_DETAILS_REQUEST';
export const FETCH_JOB_DETAILS_SUCCESS = 'FETCH_JOB_DETAILS_SUCCESS';
export const FETCH_JOB_DETAILS_FAILURE = 'FETCH_JOB_DETAILS_FAILURE';

export const APPLY_FOR_JOB_REQUEST = 'APPLY_FOR_JOB_REQUEST';
export const APPLY_FOR_JOB_SUCCESS = 'APPLY_FOR_JOB_SUCCESS';
export const APPLY_FOR_JOB_FAILURE = 'APPLY_FOR_JOB_FAILURE';

export const BOOKMARK_JOB_REQUEST = 'BOOKMARK_JOB_REQUEST';
export const BOOKMARK_JOB_SUCCESS = 'BOOKMARK_JOB_SUCCESS';
export const BOOKMARK_JOB_FAILURE = 'BOOKMARK_JOB_FAILURE';

export const FETCH_BOOKMARKED_JOBS_REQUEST = 'FETCH_BOOKMARKED_JOBS_REQUEST';
export const FETCH_BOOKMARKED_JOBS_SUCCESS = 'FETCH_BOOKMARKED_JOBS_SUCCESS';
export const FETCH_BOOKMARKED_JOBS_FAILURE = 'FETCH_BOOKMARKED_JOBS_FAILURE';
